name: Deployment Pipeline

on:
    push:
        branches:
            - main

jobs:
    deployment_pipeline:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Lint code
              run: npm run eslint
